Yak.Web/Models/AnswerForm.cs
using Yak.DTO;

namespace Yak.Web.Models
{
    public class AnswerForm
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string Content { get; set; }

        public AnswerForm(Answer answer)
        {
            Id = answer.Id;
            QuestionId = answer.QuestionId;
            Content = answer.Content;
        }

        public AnswerForm()
        {
        }

        public Answer ToDto()
        {
            return new Answer
            {
                Id = Id,
                Content = Content,
                QuestionId = QuestionId
            };
        }
    }
}

Yak.Web/Models/AnswerViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Yak.DTO;

namespace Yak.Web.Models
{
    public class AnswerViewModel
    {
        public Answer Answer { get; set; }
        public IList<CommentViewModel> CommentViewModels { get; set; }
        public int QuestionId { get; set; }

        public AnswerViewModel()
        {
            Answer = new Answer();
        }

        public AnswerViewModel(Answer answer)
        {
            Answer = answer;
            CommentViewModels = new List<CommentViewModel>();

            foreach (var comment in answer.Comments)
            {
                CommentViewModels.Add(new CommentViewModel(comment));
            }
        }

        public AnswerViewModel(int questionId, int userId)
        {
            QuestionId = questionId;
            Answer = new Answer();
        }
        public bool HasUserAlreadyVotedUp(int userId)
        {
            return Answer.Votes.Any(v => v.User.Id == userId && v.PointValue);
        }

        public bool HasUserAlreadyVotedDown(int userId)
        {
            return Answer.Votes.Any(v => v.User.Id == userId && !v.PointValue);
        }

    }
}

Yak.Web/Controllers/AnswerController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Yak.DTO;
using Yak.Services.Interfaces;
using Yak.Web.BaseUtils;
using Yak.Web.Models;

namespace Yak.Web.Controllers
{
    public class AnswerController : BaseController
    {
        private readonly IService<Answer> _answerService;
        private readonly IService<Question> _questionService;
        private readonly IService<Vote> _voteService;

        public AnswerController(
            IService<Answer> answerService,
            IService<Question> questionService,
            IService<Vote> voteService)
        {
            _answerService = answerService;
            _questionService = questionService;
            _voteService = voteService;
        }

        public ActionResult PostAnswer(AnswerViewModel answerViewModel)
        {
            _answerService.Add(new Answer
            {
                Author = User.DatabaseUser,
                Content = answerViewModel.Answer.Content,
                CreateDate = DateTime.UtcNow,
                LastModificationDate = DateTime.UtcNow,
                QuestionId = answerViewModel.QuestionId
            });
            
            return RedirectToAction("View", new { controller = "Question", id = answerViewModel.QuestionId });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var answer = _answerService.GetById(id);

            return View("AnswerForm", new AnswerForm(answer));
        }

        [HttpPost]
        public ActionResult Edit(AnswerForm answerForm)
        {
            var dto = answerForm.ToDto();
            var originalAnswer = _answerService.GetById(answerForm.Id);

            originalAnswer.Content = answerForm.Content;
            originalAnswer.LastModificationDate = DateTime.UtcNow;

            _answerService.Update(originalAnswer);

            return RedirectToAction("View", new { id = dto.QuestionId, controller = "Question" });
        }

        public JsonResult VoteUp(int answerId)
        {
            var newVote = new Vote
            {
                PointValue = true,
                User = User.DatabaseUser
            };

            _voteService.Add(newVote);

            var answer = _answerService.GetById(answerId);
            answer.Votes.Add(newVote);

            var voteDown = answer.Votes.SingleOrDefault(v => v.User.Id == User.DatabaseUser.Id && !v.PointValue);

            if (voteDown != null)
            {
                answer.Votes.Remove(voteDown);
                _voteService.Delete(voteDown);
            }

            var allVotesUp = answer.Votes.Count(v => v.PointValue);
            var allVotesDown = answer.Votes.Count(v => !v.PointValue);

            answer.RankPoint = allVotesUp - allVotesDown;

            _answerService.Update(answer);

            return Json(new { rankPoint = answer.RankPoint });
        }

        public JsonResult VoteDown(int answerId)
        {
            var newVote = new Vote
            {
                PointValue = false,
                User = User.DatabaseUser
            };

            _voteService.Add(newVote);

            var answer = _answerService.GetById(answerId);
            answer.Votes.Add(newVote);

            var voteUp = answer.Votes.SingleOrDefault(v => v.User.Id == User.DatabaseUser.Id && v.PointValue);

            if (voteUp != null)
            {
                answer.Votes.Remove(voteUp);
                _voteService.Delete(voteUp);
            }

            var allVotesUp = answer.Votes.Count(v => v.PointValue);
            var allVotesDown = answer.Votes.Count(v => !v.PointValue);

            answer.RankPoint = allVotesUp - allVotesDown;

            _answerService.Update(answer);

            return Json(new { rankPoint = answer.RankPoint });
        }

        public JsonResult MarkAnswer(int answerId, bool isCorrect)
        {
            var answer = _answerService.GetById(answerId);

            if (answer.Author.Id != User.DatabaseUser.Id)
            {
                throw new Exception("Unauthorized user tries to accept others user answer!");
            }

            answer.IsCorrect = isCorrect;

            _answerService.Update(answer);

            return Json(new { Result = true });
        }
    }
}

Yak.Web/Controllers/CommentController.cs
using System.Linq;
using System.Web.Mvc;
using Yak.DTO;
using Yak.Services.Interfaces;
using Yak.Web.BaseUtils;
using Yak.Web.Models;

namespace Yak.Web.Controllers
{
    public class CommentController : BaseController
    {
        private readonly IService<Comment> _commentService;
        private readonly IService<Answer> _answerService;
        private readonly IService<Vote> _voteService;

        public CommentController(
            IService<Comment> commentService,
            IService<Answer> answerService,
            IService<Vote> voteService)
        {
            _commentService = commentService;
            _answerService = answerService;
            _voteService = voteService;
        }

        [HttpPost]
        public ActionResult AddComment(CommentForm commentForm)
        {
            var dto = commentForm.ToDto();

            dto.Author = User.DatabaseUser;

            _commentService.Add(dto);

            var questionId = dto.QuestionId.HasValue ? dto.QuestionId.Value : _answerService.GetById(commentForm.AnswerId.Value).QuestionId;

            return RedirectToAction("View", new { id = questionId, controller = "Question" });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var comment = _commentService.GetById(id);

            return View("CommentForm", new CommentForm(comment));
        }

        [HttpPost]
        public ActionResult Edit(CommentForm commentForm)
        {
            var dto = commentForm.ToDto();

            _commentService.Update(dto);

            var questionId = dto.QuestionId.HasValue ? dto.QuestionId.Value : _answerService.GetById(commentForm.AnswerId.Value).QuestionId;

            return RedirectToAction("View", new { id = questionId, controller = "Question" });
        }

        public JsonResult VoteUp(int commentId)
        {
            var newVote = new Vote
            {
                PointValue = true,
                User = User.DatabaseUser
            };

            _voteService.Add(newVote);

            var comment = _commentService.GetById(commentId);
            comment.Votes.Add(newVote);

            var voteDown = comment.Votes.SingleOrDefault(v => v.User.Id == User.DatabaseUser.Id && !v.PointValue);

            if (voteDown != null)
            {
                comment.Votes.Remove(voteDown);
                _voteService.Delete(voteDown);
            }

            var allVotesUp = comment.Votes.Count(v => v.PointValue);
            var allVotesDown = comment.Votes.Count(v => !v.PointValue);

            comment.RankPoint = allVotesUp - allVotesDown;

            _commentService.Update(comment);

            return Json(new { rankPoint = comment.RankPoint });
        }

        public JsonResult VoteDown(int commentId)
        {
            var newVote = new Vote
            {
                PointValue = false,
                User = User.DatabaseUser
            };

            _voteService.Add(newVote);

            var comment = _commentService.GetById(commentId);
            comment.Votes.Add(newVote);

            var voteUp = comment.Votes.SingleOrDefault(v => v.User.Id == User.DatabaseUser.Id && v.PointValue);

            if (voteUp != null)
            {
                comment.Votes.Remove(voteUp);
                _voteService.Delete(voteUp);
            }

            var allVotesUp = comment.Votes.Count(v => v.PointValue);
            var allVotesDown = comment.Votes.Count(v => !v.PointValue);

            comment.RankPoint = allVotesUp - allVotesDown;

            _commentService.Update(comment);

            return Json(new { rankPoint = comment.RankPoint });
        }
    }
}

Yak.Web/Views/Shared/Answer.cshtml
@model Yak.Web.Models.AnswerViewModel
@using (Html.BeginForm("PostAnswer", "Answer"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.QuestionId)
    <h2>Your Answer</h2>
    <div>
        <div class="mdd_toolbar"></div>
        @Html.TextAreaFor(model => model.Answer.Content, new { @class = "mdd_editor form-control asnwer-editor-content" })
        <br />
        <input type="button" class="btn btn-default toggle-preview" value="Show/Hide preview" />
        <div class="markup-preview-box" style="display: none;">
            <h4>Preview:</h4>
            <div class="mdd_preview"></div>
        </div>
        <hr/>
        <input type="submit" value="Post your Answer" class="btn btn-success" style="width: 100%;" />
    </div>
}

<script type="text/javascript" src="@Url.Content("~/Scripts/MarkdownDeepLib.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/Answer/NewAnswer.js")"></script>
<script type="text/javascript">
    PrepareMarkdownEditor();
</script>

Yak.Web/Views/Shared/AnswersList.cshtml
@using Humanizer
@using Yak.Web.Utils
@model IList<Yak.Web.Models.AnswerViewModel>

@foreach (var answer in Model)
{
    var blockVoteUpOption = answer.HasUserAlreadyVotedUp(User.DatabaseUser.Id);
    var blockVoteDownOption = answer.HasUserAlreadyVotedDown(User.DatabaseUser.Id);
    var isAuthorOfQuestion = (bool)Html.ViewData["IsAuthorOfQuestion"];
    var isAnyOtherAnswerAccepted = Model.Any(a => a.Answer.IsCorrect && a.Answer.Id != answer.Answer.Id);

    <div class="answer-details">
        <div class="vote-box">
            <div class="vote-up @if (blockVoteUpOption) { <text>vote-blocked</text> }" data-answerId="@answer.Answer.Id"><i class="fa fa-angle-up fa-3 size-3em"></i></div>
            <div class="votes-count"><span style="font-size: 2em;">@answer.Answer.RankPoint</span></div>
            <div class="vote-down @if (blockVoteDownOption) { <text>vote-blocked</text> }" data-answerId="@answer.Answer.Id"><i class="fa fa-angle-down fa-3 size-3em"></i></div>
            <div class="answer-correct @if (!isAuthorOfQuestion || isAnyOtherAnswerAccepted) { <text>hidden</text> } @if (@answer.Answer.IsCorrect) { <text>accepted</text> } else { <text>not-accepted</text> } " data-answerId="@answer.Answer.Id"><i class="fa fa-check fa-3 size-3em"></i></div>
        </div>
        <div class="answer-content">
            <div class="answer-author-details pull-right col-md-2 text-center">
                <img width="82" height="82" src="@Url.Content("~/Content/images/user128.png")" />
                <div>@answer.Answer.LastModificationDate.Humanize(true, null, System.Globalization.CultureInfo.InvariantCulture)</div>
                <div>by</div>
                <div>@answer.Answer.Author.Username</div>
            </div>
            @Html.TransformToMarkdown(@answer.Answer.Content)
            <div class="clearfix">
                <div class="clearfix"></div>
                <div class="answer-actions">
                    <span class="label label-default add-comment">ADD COMMENT</span>
                    @if (answer.Answer.Author.Id == User.DatabaseUser.Id)
                    {
                        @:•
                        @Html.ActionLink("Edit", "Edit", new { id = answer.Answer.Id, controller = "Answer" })
                    }
                </div>
                <div class="answer-comments" style="margin-top: 5px;">
                    @Html.Partial("CommentsList", answer.CommentViewModels)
                    <div class="comment-editor hidden" style="margin-top: 10px;">
                        @using (Html.BeginForm("AddComment", "Comment", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("AnswerId", answer.Answer.Id)
                            @Html.TextArea("Content", new { @class = "form-control", @name = "Content", @id = "CommentContent", @style = "margin-bottom: 5px" })
                            <input type="submit" value="add comment" class="btn btn-success" />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />
}

<script type="text/javascript">
    $(".answer-details .vote-box .vote-up").click(function () {
        var self = $(this);
        var answerId = $(this).attr("data-answerId");
        var $votesCountElement = $(this).parent().find(".votes-count span");

        if ($(this).hasClass("vote-blocked")) return;

        $.ajax(
            {
                url: '@Url.Action("VoteUp", "Answer")',
                data: { "answerId": answerId },
                dataType: "json",
                method: "post",
                success: function (data) {
                    $votesCountElement.text(data.rankPoint);
                    self.addClass("vote-blocked");
                    self.parent().find(".vote-down").removeClass("vote-blocked");
                }
            });
    });

    $(".answer-details .vote-box .vote-down").click(function () {
        var self = $(this);
        var answerId = $(this).attr("data-answerId");
        var $votesCountElement = $(this).parent().find(".votes-count span");

        if ($(this).hasClass("vote-blocked")) return;

        $.ajax(
            {
                url: '@Url.Action("VoteDown", "Answer")',
                data: { "answerId": answerId },
                dataType: "json",
                method: "post",
                success: function (data) {
                    $votesCountElement.text(data.rankPoint);
                    self.addClass("vote-blocked");
                    self.parent().find(".vote-up").removeClass("vote-blocked");
                }
            });
    });

    $(".answer-actions > span.add-comment").click(function () {
       $(this).parent().parent().find(".answer-comments .comment-editor").removeClass("hidden");
    });

    $(".answer-correct").click(function () {
        var self = $(this);
        var answerId = $(this).attr("data-answerId");
        var isAlreadyAccepted = $(this).hasClass("accepted");

        if (self.hasClass("hidden")) { return; }

        $.ajax(
        {
            url: '@Url.Action("MarkAnswer", "Answer")',
            data: { "answerId": answerId, "isCorrect": !isAlreadyAccepted },
            dataType: "json",
            method: "post",
            success: function (data) {
                if (isAlreadyAccepted)
                {
                    self.removeClass("accepted");
                }
                else 
                {
                    self.addClass("accepted");
                }
            }
        });
    });
</script>

Yak.Web/Views/Shared/CommentsList.cshtml
@model IList<Yak.Web.Models.CommentViewModel>

@using Humanizer

@foreach (var comment in Model)
{
    var blockVoteUpOption = comment.HasUserAlreadyVotedUp(User.DatabaseUser.Id);
    var blockVoteDownOption = comment.HasUserAlreadyVotedDown(User.DatabaseUser.Id);

    <hr style="margin-top:5px; margin-bottom:5px;" />
    <div class="comment-details" style="padding: 5px 5px 5px 5px;">
        <div class="vote-box-small">
            <div class="vote-up @if (blockVoteUpOption) { <text>vote-blocked</text> }" data-commentId="@comment.Comment.Id"><i class="fa fa-angle-up fa-3 size-1em"></i></div>
            <div class="votes-count"><span style="font-size: 1em;">@comment.Comment.RankPoint</span></div>
            <div class="vote-down @if (blockVoteDownOption) { <text>vote-blocked</text> }" data-commentId="@comment.Comment.Id"><i class="fa fa-angle-down fa-3 size-1em"></i></div>
        </div>
        <div class="comment-content" style="min-height:4.3em; overflow: auto;">
            <p>@Html.Raw(comment.Comment.Content)</p>
            <div>
                <span style="float:right;">@comment.Comment.LastModificationDate.Humanize(true, DateTime.UtcNow, System.Globalization.CultureInfo.InvariantCulture) by @comment.Comment.Author.Username</span>
            </div>
            <div class="clearfix">
                <div class="clearfix"></div>
                
                <div class="comment-actions">
                    @if (comment.Comment.Author.Id == User.DatabaseUser.Id)
                    {
                        // TODO: delete option
                    }
                </div>
            </div>
        </div>
    </div>
}